version: "2"

run:
  concurrency: 4
  go: "1.24"
  tests: true
  allow-parallel-runners: true

linters:
  enable:
    - cyclop
    - gosec
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    
    rules:

      - linters: 
          - staticcheck
        path: test.go

formatters:
  enable:
    - gci
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
