name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    name: Build
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      packages: read
      security-events: read
      pull-requests: read

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Build
      run: go build -v .

    - name: Test
      run: CGO_ENABLED=1 go test -v -race ./... -covermode=atomic -coverprofile=coverage.out

    - name: GoLang CI Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest

  docker:

    name: Docker
    needs: build
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      packages: write
      security-events: read

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: ghcr.io/${{ github.repository }}:test

      - name: Test Docker Image
        run: |
          docker run --rm ghcr.io/${{ github.repository }}:test --help

      - name: Build and push Docker Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          provenance: mode=max
          sbom: true
          tags: ghcr.io/${{ github.repository }}:latest
          push: true

      - name: Delete untagged images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
